include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml

stages:
  - test
  - release

docker-dev-image:
  stage: release
  image: docker:20
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:20-dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:dev .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:dev
  only:
    - master

semantic-release:
  stage: release
  image: docker:20
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:20-dind
  before_script:
    - docker build --tag $CI_REGISTRY_IMAGE:latest .
    - apk add nodejs npm git python3 py3-pip py3-setuptools py3-wheel py3-twine
    - npm install --legacy-peer-deps -g semantic-release @semantic-release/gitlab-config @semantic-release/changelog semantic-release-pypi@2.4.2 @semantic-release/exec @semantic-release-plus/docker
  script:
    - semantic-release
  only:
    - master
    - schedules
