---
branch: master
extends: '@semantic-release/github'
tagFormat: "${version}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"
  - "semantic-release-pypi"
  - ["@semantic-release-plus", { name: bitcast/mumbleice }]
