branches:
  - main
tagFormat: '${version}'
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  - 'semantic-release-pypi'
  - ['@semantic-release-plus/docker', { name: bitcast/mumbleice }]
