branches:
  - master
extends: '@semantic-release/gitlab-config'
tagFormat: '${version}'
plugins:
  - '@semantic-release/changelog'
  - 'semantic-release-pypi'
  - '@semantic-release/exec':
    prepareCmd: 'docker build -t bitcast/mumbleice .'
  - 'semantic-release-docker':
    name: bitcast/mumbleice
