name: "Semantic release composite action"
description: "Checks out the repository and installs NPM plus run tests"
runs:
  using: "composite"
  steps:
  - uses: actions/setup-node@v1
    with:
      node-version: "16.x"
  - run: npm ci
  - run: npm run build --if-present
  - run: npm test
  - run: npx semantic-release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  - shell: bash
