name: Release
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y python3 python3-pip python3-setuptools twine

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            semantic-release-pypi
            @semantic-release-plus/docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
