on: [push, pull_request]
  branches:
  - master

jobs:
  docker-dev-image:
    runs-on: ubuntu-latest
    env:
      CI_REGISTRY_IMAGE: bitcast/mumbleice 
    container: docker:20
    
    services:
      docker:
        image: docker:20-dind
        env:
          DOCKER_DRIVER: overlay2

    steps:
      - name: Check out repositrory code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ CI_REGISTRY_IMAGE}}:dev
