on:
  push:
    branches:
      - main
  pull:
    branches:
      - main

jobs:
  docker-dev-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repositrory code
        uses: actions/checkout@v2

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ${{ secrets.CI_REGISTRY_IMAGE }}
          tags: dev, ${{ github.sha }}
          registry: docker.io
          dockerfile: ./Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
